pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.neoforged.gradle.userdev') {
                useModule("net.neoforged.gradle:userdev:${requested.version}")
            }
        }
    }
}
