modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-design-n-decor"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"
# [[accessTransformers]]
# file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
# NONE - BEFORE - AFTER
ordering="NONE"
# BOTH - CLIENT - SERVER
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="flywheel"
type="required"
versionRange="${flywheel_version_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="ponder"
type="required"
versionRange="[0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.9,6.1.0)"
ordering="AFTER"
side="BOTH"
